# Jekyll config.
# NOTE: In dev env you have to restart the dev server for the changes to take place

# TODO: change default values to whatever you need below:
title: TourHunter Help Center
email: hello@tourhunter.com
description: 'TourHunter Help Center'

repository: tourhunter-com/help-tourhunter-com

timezone: UTC
encoding: "utf-8"

# URLs and links
baseurl: ''
url: 'https://help.tourhunter.com'

# Collections
collections:
 en:
  output: true
  permalink: /en/:path/
 ru:
  output: true
  permalink: /ru/:path/

defaults:
 #languages
 -
  scope:
   path: ""
   type: "en" # collection, @see https://jekyllrb.com/docs/configuration/front-matter-defaults/
  values:
   lang: "en"
 -
  scope:
   path: ""
   type: "ru"
  values:
   lang: "ru"

# Build settings
theme: jekyll-theme-cayman
markdown: kramdown

plugins:
- jekyll-feed
- jekyll-github-metadata

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - .idea/
 - CNAME
 - README.md
 - PULL_REQUEST_TEMPLATE.md
 - ISSUE_TEMPLATE.md
 - LICENSE.md
 - CODE_OF_CONDUCT.md
 - CONTRIBUTING.md
 - INSTALL.md
